config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts, only: [:show, :edit, :update, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader
  validates :user_id, presence: true
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :content, presence: true, length: { minimum: 10 }
  validate  :image_size

  private

  def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:show, :create, :destroy]
  before_action :correct_user,   only: :destroy

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end
  private

  def post_params
    params.require(:post).permit(:title, :content, :image)
  end

  def correct_user
   @post = current_user.posts.find_by(id: params[:id])
   redirect_to root_url if @post.nil?
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content">
    <br>
    <b><em>Title:</em></b> <!-- ne trozh syka, seriy -->
    <%= post.title %><br>

    <b><em>Content:</em></b> <!-- ce tozhe -->
    <%= post.content %>
  </span>
  <span class="timestamp">
    <p class="normal-text-rght small-text">
      Posted <%= time_ago_in_words(post.created_at) %> ago.
    </p>
    <% if logged_in? %>

    <div class="center">
      <%= link_to "Show", post_path(post), class: "btn btn-primary marg-bottom-post" %>
      <% if current_user?(post.user) %>

        <%= link_to "Edit", edit_post_path(post), class: "btn btn-primary marg-bottom-post" %>
        <%= link_to "Delete", post, method: :delete,
                                         data: { confirm: "You sure?" }, class: "btn btn-primary marg-bottom-post" %>
      <% end %>
    <% end %>
    </div>
  </span>
</li>
<hr> <!-- bottom line from every post -->

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= form_with(model: @post, local: true) do |form| %>
<div class="row center">
  <div class="col-md-6 col-md-offset-3 mx-auto">
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user?(@post.user) %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :content %><br>
      <%= form.text_area :content, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :image %><br>
      <%= form.file_field :image, class: 'form-control' %>
    </p>

    <p>
      <%= form.submit "Update Post", class: "btn btn-primary" %>
    </p>

    <%= link_to 'Back', post_path(@post) %>


  <% else %>
  <%= link_to 'Create new Post', root_path %>
  <% end %>
<% end %>
</div>
</div>

app/views/posts/show.html.erb
<div class="jumbotron">
  <div class="">
    <strong>Author:</strong>
    <%= @post.user.name %>
  </div>
  <div class="">
    <strong>Title:</strong>
    <%= @post.title %>
  </div>
  <div class="">
    <strong>Content:</strong>
    <%= @post.content %>
  </div>
  <div class="">
    <strong>Image:</strong>
     <%= image_tag(@post.image_url) if @post.image? %>
  </div>
</div>

  <h2>Comments</h2>
  <%= render @post.comments %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

  <div class="center">
    <% if current_user?(@post.user) %>
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <% end %>
      <%= link_to 'Back', user_path(@post.user) %>
  </div>